PresentMon.cpp
PresentMon.hpp
PresentMonEtw.cpp
TraceSession.cpp
TraceSession.hpp
main.cpp

Adds support for writing to an ETL file in addition to the real-time monitoring, or alternatively parsing an already existing ETL file (e.g. converting from ETL to present list in CSV format). The real-time monitoring only works correctly when the processes in the ETL are still running, since it still uses real-time OpenProcess techniques to convert from the PID in the events to useful info.
There's several bugfixes here too. A primary focus was around ensuring events are written to the CSV in order, to prevent super large (negative) deltas. There are also some assertion cleanups, fixes to events being discarded when they shouldn't and not discarded when they should, and a rare double-completion issue which caused framerates and deltas to come up incorrect.

Add basic ETL file support and fix a bunch of bugs, especially focusing around the CSVs.

---

PresentMon.cpp
PresentMon.hpp
PresentMonEtw.cpp
main.cpp

Adds delayed startup, timed runs, logging only while scroll lock is active. Fixes issues related to exiting. Adds ability to get process info from ETL file instead of realtime APIs. Fix DWM presents getting lost on MPO systems (which also resulted in all blit model or composition buffer presents getting lost).

Polish up ETL file support, add some quality-of-life functionality, and more bugfixes

---

PresentMon.hpp
PresentMonEtw.cpp

Some D3D9 apps were either getting bad data or crashing when in fullscreen, due to a bad assumption about all apps having a valid HWND.

Minor bugfixes

---

PresentMon.cpp
PresentMonEtw.cpp
main.cpp

Don't require administrator privileges for reading from file, and fix up the timestamp column instead of using real-time QPC.

Some quality-of-life fixes for ETL file support

---

PresentMon.cpp
PresentMon.hpp
PresentMonEtw.cpp
main.cpp

This reverts behavior back to pretty much right after my first commit to the project. There are still scenarios where PresentMon is not robust enough to handle full system capture (e.g. out-of-order present completion in multi-GPU scenarios, or swapchain re-creation which gets the same address). In scenarios where it breaks due to issues like these, running with "-simple" will turn off all advanced tracking and just capture fraps-like data.
Should resolve issue #11.

Add "simple" mode to PresentMon.

---

PresentMon.cpp
PresentMon.hpp
README.md
main.cpp

This was useful for us incorporating PresentMon in some automated benchmarking, where the app runs a fixed scene and then terminates. We want PresentMon to terminate when the app does.

Add -terminate_on_proc_exit command line parameter.

---

PresentData/DxgkrnlEventStructs.hpp
PresentData/PresentData.vcxproj
PresentData/PresentData.vcxproj.filters
PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp
PresentData/SwapChainData.cpp
PresentMon/PresentMon.cpp
PresentMon/TraceSession.cpp
PresentMon/tracesession.hpp

Add Win7 support. This should address #30. I've tested D3D9, DXGI, and Vulkan apps on Win7, both in realtime and from an ETL file. The interesting thing here is adding support for Win7's DxgKrnl/DWM provider data, which is somewhat different from Win8+. Additionally, I verified that PresentMon correctly handles DWM-off scenarios, which don't (really) exist on Win8+.
I did my best to regression test what I could. Let me know if you have specific scenarios I should try, or if you find things that are broken.

Add Win7 support.

---

PresentData/KernelTraceControl.h
PresentData/MixedRealityTraceConsumer.cpp
PresentData/MixedRealityTraceConsumer.hpp
PresentData/PresentData.vcxproj
PresentData/PresentData.vcxproj.filters
PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp
PresentData/TraceConsumer.cpp
PresentData/TraceConsumer.hpp
PresentMon/PresentMon.cpp
PresentMon/PresentMon.vcxproj

Implements #55 
This provider consists purely of events that were injected into ETL files during the merge process. On the machine doing the merge, TDH is queried and the resulting metadata is included in the stream, so events can be decoded on machines which don't have the same version of ETW manifests as the one which produced the ETL.
Windows Performance Toolkit comes with a KernelTraceControl.h containing the definition of the metadata provider GUID and the opcode value for the metadata events. These events payload a TRACE_EVENT_INFO struct for some other provider/event.
Unfortunately, TDH doesn't have APIs for decoding based on a provided TRACE_EVENT_INFO, only ones which operate on an internally-located TRACE_EVENT_INFO from (e.g.) an XML manifest. So the payload parsing has to be …

Add support for consuming XPerf's metadata provider.

---

PresentMon/Console.cpp

There are displayCount latency values.
To calculate average correct denominator is displayCount rather than displayCount - 1

Update latency average calculation

---

PresentData/MixedRealityTraceConsumer.cpp
PresentData/MixedRealityTraceConsumer.hpp
PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp
PresentMon/OutputThread.cpp

PresentData's destructor has asserts to catch incomplete events being destroyed. While this can be useful scenarios, it creates unexpected behaviors when these events are copied for diagnostic or record-keeping purposes.
My perspective is that this assert is better done in the debugger to keep the code clean and easy to use.
Alternatively, additional flags could help as a workaround, but isn't as clean.

Allow PresentEvents to be constructed and removed like a PoD type

---

PresentData/ETW/Microsoft_Windows_DxgKrnl.h
PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp

There are cases where a Present Blit can be optimized out in kernel. In such cases, we return success to the caller, but issue no further work for the present, leaving PresentMon to see these as outstanding. A future OS release will issue a new ETW event when such a scenario occurs. This change detects this new event and marks the present as discarded.
Signed-off-by: Jeff Wickenheiser <jeffwick@microsoft.com>

Add support for Blit Cancel events

---

PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp
PresentMon/TraceSession.cpp

This change allows PresentMon data collection to be scoped to specified processes (currently only supporting process ids). This reduces memory usage by not tracking unnecessary presents from other processes, improving beyond the current implementation where filtering is just applied to the output.
Signed-off-by: Jeff Wickenheiser jeffwick@microsoft.com

Add ability to scope data collection to specified process id

---

Tests/GoldEtlCsvTests.cpp

printf has inconsistent rounding behavior accross different platforms, see:
https://www.exploringbinary.com/inconsistent-rounding-of-printed-floating-point-numbers/
This PR adds some comparison code to tolerate rounding errors on the smallest decimal point.
Previously, tests cases 0 and 3 returns respectively:
GoldEtlCsvTests.cpp(110): error: Difference on line: 326
COLUMN                    TEST VALUE                            GOLD VALUE
MsUntilDisplayed          16.312                                  16.313
GoldEtlCsvTests.cpp(110): error: Difference on line: 119
COLUMN                    TEST VALUE                            GOLD VALUE
MsInPresentAPI             0.062                                    0.063
Now both tests pass. Validated via printing that this path is only stepped …

Fix failures in Gold Csv caused by platform-dependent printf rounding

---

PresentData/PresentMonTraceConsumer.cpp

In rare scenarios, CompletePresent could enter into an infinite loop due to a flaw in CompletePresent's logic.
This is mainly due to the logic to complete presents in chronological order missing an edge case.
The case is as follows:
Present 1: Unknown state, Incomplete
Present 2: Discarded state, Complete
Present 3: Unknown state, incomplete
When present 3 completes with a Presented FinalState, it will attempt to drain Presents 1 and 2 in a while loop, it completes Present 1, but Present 2 will fail to drain because of an early return if we call CompletePresent on an already complete present.
Also remove some other logic that incorrectly assumes that a completed present will never be visited by CompletePresent again.

Prevent rare present ordering from causing CompletePresent to enter an infinite loop

---

PresentData/ETW/Microsoft_Windows_DxgKrnl.h
PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp

After some recent changes to DWM, some TokenStateChanged events can now come much later than expected. This causes iFlip presents that previously wait on that event to incorrectly become marked as dropped when a newer frame completes first.
We resolve this by allows iFlip presents to be completed without waiting on TokenStateChanged events (e.g. they can be completed by VSyncDPCMPO events). For iFlip, we don't need TokenStateChanged events to track the data we need.
This was locally validated to no longer falsely report drops on a trace NVidia submitted, and passes existing Gold Standard tests.

Fix IFlip Notify Mode where presents could be incorrectly dropped

---

PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp

Removing Composition Atlas PresentMode from PresentMon tracking as it doesn't make sense to track them (fps is invalid since they're composing various windows together) and are also not processed correctly in our current iterations of PresentMon

Removal of Composed Composition Atlas (7) PresentMode from PresentMon

---

PresentMon/OutputThread.cpp

gQuit is false when initialized, and it is set to true when do StopOutputThread().
It works fine to collect data at the first time. However, if want to collect data again, it will break cycles because gQuit is still true.

Fix issue where gQuit is not set to false when do StartOutputThread()

---

PresentData/MixedRealityTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp
PresentData/TraceSession.cpp
PresentMon/CommandLine.cpp
PresentMon/Console.cpp
PresentMon/OutputThread.cpp
Tests/PresentMonTests.h

The reason: I have project wide defined `NOMINMAX` and get macro redefinition warning. I decided to wrap it up with `#ifndef` everywhere and change WinAPI max/min calls with STL functions.

Fix: NOMINMAX macro definition with #ifndef, using std::max/std::min instead of WINAPI ones

---

PresentData/PresentMonTraceConsumer.cpp
PresentData/PresentMonTraceConsumer.hpp
PresentData/PresentMonTraceSession.cpp
PresentMon/CommandLine.cpp
PresentMon/CsvOutput.cpp
PresentMon/MainThread.cpp
PresentMon/PresentMon.hpp

backpressure
frame id
screen time absolute
closes #313 
closes #312

Backpressure and other options for PresentData debugging

---

IntelPresentMon/PresentMonAPI2Tests/CsvHelper.h
IntelPresentMon/PresentMonMiddleware/FrameEventQuery.cpp
IntelPresentMon/PresentMonMiddleware/FrameEventQuery.h

FrameTime calculation fix.
closes #311

Fix for incorrect FrameTime metric calculation.

---

PresentMon/CsvOutput.cpp

Flushes were accidentally removed at some point.  v2.0.1 added them back in, but only for the --use_v1_metrics CSV.  This change adds them back in for the default CSV as well.
Fixes #232

Add fflush to ConsoleApplication 2.0 metrics csv

---

PresentData/PresentMonTraceConsumer.cpp

Fixed Win11 issue where multiple retrieve message events were being received and this was causing us to not correctly apply the xform message. Also fine tuned the mouse click threshold.

Fix Win11 bug found on Witcher3

---

IntelPresentMon/PresentMonService/RealtimePresentMonSession.cpp

The deferral time limit was not being set for real time captures which was causing deferred presents to incorrectly be classified as lost when cleaning up "stale deferred frames" in CompletePresent.

Set deferral time limit for IPM

---

IntelPresentMon/CommonUtilities/cli/CliFramework.h
IntelPresentMon/PresentMonAPIWrapperCommon/Exception.cpp
IntelPresentMon/SampleClient/CliOptions.h
IntelPresentMon/SampleClient/SampleClient.args.json
IntelPresentMon/SampleClient/SampleClient.cpp

enabling sample client to be used with presentmon servers other than the default globally installed service after the new loader update

allow specifying middleware path in sample client & better wrapper errs

---

PresentData/PresentMonTraceConsumer.cpp

Current CB size starts dropping frames at greater than 700 fps. Increasing size to accommodate framerates up to 1000 FPS.

Updating CB Size

---

PresentData/PresentMonTraceConsumer.cpp

The way PresentMon marks the completion of frames is to first mark frames as 'Presented' when it receives MMIO MPO flip call and then once Win32k providers’ (running within DWM process) TokenStateChange(TokenState::Discarded) event is received it is marked as completed.
In certain cases, like when there are short bursts of presents, we get multiple back-to-back flips and token tracking thread ends up marking the first frame in the burst as dropped. To fix this issue, we mark the frame as discarded only if the frame already doesn’t have valid ScreenTime.
ETL file: https://drive.google.com/file/d/1uVnWiT9An-p5_BanYQB8e_-FCPd61qXP/view?usp=sharing

Fix frames that are marked as discarded incorrectly
